# Obrigatório para o SonarCloud. Geralmente é o seu nome de usuário do GitHub.
sonar.organization=sauloam

# Identificador único do seu projeto no SonarQube/SonarCloud
sonar.projectKey=desafio-pleno

# Nome do projeto que aparecerá na UI do SonarQube
sonar.projectName=desafio-pleno-api

# Caminho para o código-fonte da sua API Python
sonar.sources=app

# Define o host do seu SonarQube. Para o SonarCloud, use https://sonarcloud.io
sonar.host.url=https://sonarcloud.io