name: 'Terraform Deploy GCP'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform GCP'
    runs-on: ubuntu-latest
    env:
      # Diretório onde os arquivos do Terraform estão
      TF_WORKING_DIR: 'infra'

    # Permissões necessárias para o OIDC se comunicar com o GCP
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # O caminho completo para o seu Workload Identity Provider
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          # O e-mail da Service Account que o Terraform irá usar
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init

      - name: Terraform Plan
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' # Aplicar somente na branch main
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve