{
 "title": "API-PY Metrics",
 "tags": [ "api-py" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_requests_total{job=\"default/api-py-service\"}[5m])) by (method, status)",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "P99 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_requests_latency_seconds_bucket{job=\"default/api-py-service\"}[5m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_requests_exceptions_total{job=\"default/api-py-service\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}