name: App Build & Deploy

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE_TAG: us-central1-docker.pkg.dev/projeto-globo-489614/desafio-pleno-repo/api-py:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool-globo/providers/github-pool-globo'
          service_account: 'github-actions-sa@projeto-globo-489614.iam.gserviceaccount.com'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: desafio-pleno-cluster
          location: us-central1-a

      - name: Deploy to GKE
        run: |
          # Substitui o placeholder no arquivo yaml pela imagem real com a tag (hash do commit)
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_TAG|g" infra/k8s/deployment.yml
          kubectl apply -f infra/k8s/deployment.yml

      - name: Get Service URL
        run: |
          # Aguarda o rollout finalizar para garantir que a aplicação está rodando
          kubectl rollout status deployment/api-py

          # Loop para aguardar a atribuição do IP externo pelo LoadBalancer
          echo "Aguardando IP externo do LoadBalancer..."
          EXTERNAL_IP=""
          while [ -z "$EXTERNAL_IP" ]; do
            sleep 10
            EXTERNAL_IP=$(kubectl get svc api-py-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          done

          echo "✅ Deploy concluído! Acesse a API em:"
          echo "http://$EXTERNAL_IP:80/api/comment/list/1"