name: GCP Auth
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Authentication
        id: check_auth
        run: |
          ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")
          if [ -n "$ACCOUNT" ]; then
            echo "status=authenticated" >> $GITHUB_OUTPUT
          else
            echo "status=unauthenticated" >> $GITHUB_OUTPUT
          fi

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        if: steps.check_auth.outputs.status == 'unauthenticated'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'projeto-globo-489614'
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool-globo/providers/github-pool-globo'
          service_account: 'github-actions-sa@projeto-globo-489614.iam.gserviceaccount.com'

      - name: 'Verify Authentication'
        if: steps.check_auth.outputs.status == 'unauthenticated'
        run: gcloud auth list