name: GCP Auth
on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'projeto-globo'
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool-globo/providers/github-pool-globo'
          service_account: 'github-actions-sa@projeto-globo.iam.gserviceaccount.com'

      - name: 'Verify Authentication'
        run: gcloud auth list
