name: Pipeline Orchestrator

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  demo:
    uses: ./.github/workflows/github-actions-demo.yml

  sonar-scan:
    needs: demo
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

  terraform-lint:
    needs: demo
    uses: ./.github/workflows/terraform-lint.yml

  terraform-deploy:
    needs: [sonar-scan, terraform-lint]
    uses: ./.github/workflows/terraform-deploy.yml
    secrets: inherit

  app-deploy:
    needs: terraform-deploy
    uses: ./.github/workflows/app-deploy.yml
    secrets: inherit

  terraform-destroy:
    needs: app-deploy
    uses: ./.github/workflows/terraform-destroy.yml
    secrets: inherit
    secrets: inherit