name: Terraform Lint

on:
  workflow_call:

jobs:
  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'infra'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" fmt -check

      - name: Terraform Init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend=false

      - name: Terraform Validate
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          tflint -f compact