name: 'Terraform Deploy GCP'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  terraform:
    name: 'Terraform GCP'
    runs-on: ubuntu-latest
    env:
      # Diretório onde os arquivos do Terraform estão
      TF_WORKING_DIR: 'infra'

    # Permissões necessárias para o OIDC se comunicar com o GCP
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para ter o histórico do git para o revert

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # O caminho completo para o seu Workload Identity Provider
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool-globo/providers/github-pool-globo'
          # O e-mail da Service Account que o Terraform irá usar
          service_account: 'github-actions-sa@projeto-globo-489614.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create Terraform State Bucket
        run: |
          # Tenta criar o bucket se ele não existir. O comando '|| true' impede que o job falhe se o bucket já existir.
          gcloud storage buckets create gs://terraform-state-projeto-globo-489614 --location=us-central1 || true
          echo "Bucket verificado/criado."

      - name: Terraform Init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init

      - name: Terraform Plan
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' # Aplicar somente na branch main
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve

      - name: Rollback on Failure
        if: failure() && steps.apply.outcome == 'failure' # Executa apenas se o Apply falhar
        run: |
          echo "🚨 Terraform Apply falhou. Iniciando Rollback..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git revert HEAD --no-edit
          echo "🔄 Commit revertido. Reaplicando estado anterior..."
          terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color
          terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve
          echo "❌ Rollback concluído com sucesso. Falhando a pipeline para notificar erro no deploy original."
          exit 1